- name: Install Docker and Deploy Nginx
  hosts: server1
  become: true
  become_method: sudo
  vars:
    create_containers: 4
    container_name: nginx
    container_image: nginx:alpine
    container_exposed_port: 8888

  tasks:
#--------------------------------------------#
# Docker Setup
#--------------------------------------------#
    - name: Install Support package
      apt: update_cache=yes name={{ item }} state=latest
      loop: [ 'ca-certificates', 'curl', 'gnupg' ]
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Install Docker
      apt: name={{ item }} state=present
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin', 'docker-compose' ]

#--------------------------------------------#
# Docker Deploy Nginx
#--------------------------------------------#
    - name: Pull default Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: check container stat
      command: "curl localhost:{{container_exposed_port}}"
      failed_when: false
      register: container_stat

    - name: app container
      command: sudo docker run -d --name {{container_name}} -p {{container_exposed_port}}:80 {{container_image}}
      when: >
        "Connection refused" in container_stat.stderr
